# Docker Compose for Job Analytics (Simplified - JSON-based)
# Removed PostgreSQL and MongoDB - Using JSON files instead

services:

  # Jupyter Notebook
  jupyter:
    build:
      context: .
      dockerfile: docker/Dockerfile.jupyter
    container_name: job_analytics_jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/workspace
      - ./notebooks:/workspace/notebooks
      - ./output:/workspace/output
    environment:
      - JUPYTER_ENABLE_LAB=yes
    networks:
      - job_analytics_network

  # Streamlit Dashboard
  dashboard:
    build:
      context: .
      dockerfile: docker/Dockerfile.dashboard
    container_name: job_analytics_dashboard
    ports:
      - "8501:8501"
    volumes:
      - .:/workspace
      - ./output:/workspace/output
    command: streamlit run dashboard/simple_app.py
    networks:
      - job_analytics_network

  # FastAPI Backend
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: job_analytics_api
    ports:
      - "8000:8000"
    volumes:
      - .:/workspace
      - ./output:/workspace/output
    command: uvicorn api.simple_main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - job_analytics_network

  # Apache Spark (Optional for big data processing)
  # Commented out due to image availability issues
  # spark-master:
  #   image: bitnami/spark:3.4
  #   container_name: job_analytics_spark_master
  #   environment:
  #     - SPARK_MODE=master
  #     - SPARK_RPC_AUTHENTICATION_ENABLED=no
  #     - SPARK_RPC_ENCRYPTION_ENABLED=no
  #     - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
  #     - SPARK_SSL_ENABLED=no
  #   ports:
  #     - "8080:8080"
  #     - "7077:7077"
  #   networks:
  #     - job_analytics_network

  # spark-worker:
  #   image: bitnami/spark:3.4
  #   container_name: job_analytics_spark_worker
  #   environment:
  #     - SPARK_MODE=worker
  #     - SPARK_MASTER_URL=spark://spark-master:7077
  #     - SPARK_WORKER_MEMORY=2G
  #     - SPARK_WORKER_CORES=2
  #     - SPARK_RPC_AUTHENTICATION_ENABLED=no
  #     - SPARK_RPC_ENCRYPTION_ENABLED=no
  #     - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
  #     - SPARK_SSL_ENABLED=no
  #   networks:
  #     - job_analytics_network
  #   depends_on:
  #     - spark-master

networks:
  job_analytics_network:
    driver: bridge
